### ISSUE TITLE
Can't delete product from cart if there is only one product

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1789]
**Description**:
Can't delete product from cart if there is only one product

**Expected behavior**:
Product deleted

**To Reproduce**:
1. Open product page
2. Add to cart
3. Open mini-cart
4. Tap delete

**Actual result**:
Error message is displayed
![image](https://user-images.githubusercontent.com/73526235/100622359-71272a80-3329-11eb-9baa-35bf9668cd09.png)

**Additional context**:
It disappears from cart if we refreshed page or added new product

**Comment by magexpert** [comment]
Same issue detected here.

 

Van: aleksandrakorolova <notifications@github.com>
Beantwoorden - Aan: scandipwa/base-theme <reply@reply.github.com>
Datum: maandag 30 november 2020 om 15:31
Aan: scandipwa/base-theme <base-theme@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [scandipwa/base-theme] Can't delete product from cart if there is only one product (#1789)

 

Description:
Can't delete product from cart if there is only one product

Expected behavior:
Product deleted

To Reproduce:
Open product page
Add to cart
Open mini-cart
Tap delete
Actual result:
Error message is displayed

Additional context:
It disappears from cart if we refreshed page or added new product

**Comment by aleksandrakorolova** [comment]
Can't reproduce on ScandiPWA 3.2.4
