### ISSUE TITLE
Mobile: Opera: Sometimes title and part of page blink on write review page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1884]
**Description**:
Title and part of page blink on write review page

**Expected behavior**:
Title doesn't blink
![Screenshot_20201215-085758_Opera](https://user-images.githubusercontent.com/73526235/102181951-1a3a5d00-3eb4-11eb-8568-fa4755a1d14b.jpg)

**To Reproduce**:
1. Open product page
2. Tap 'Write new review'
3. Scroll down/up (hide URL)

**Actual result**:
Title and part of page blink
https://drive.google.com/file/d/12AASYU1yob4U_vLR2gj9iGGUc9X6osZn/view?usp=sharing

**Additional context**:
v 61.1.3067.56625
Samsung s10e (v10)

**Comment by tatiana-scandi** [comment]
Didn't manage to reproduce the issue on Android device and iOS device, browser Opera.

Moreover, now Back button + Product name are displayed on top header, while when the bug was reported there were Close button and "Write a review message" at the same place. Probably the update has already fixed the issue indirectly.  
![photo_2021-02-24_22-12-40](https://user-images.githubusercontent.com/79456428/109053401-b4592580-76ed-11eb-981d-42ec806d4b86.jpg)

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2252
