### ISSUE TITLE
The estimated shipping price doesn't change to $0.00 if user used free shipping coupon in the cart

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2081]
**Description**:
The estimated shipping price doesn't change to $0.00 if user used free shipping coupon in the cart

**Expected behavior**:
Shipping price changes to see shipping ($0.00)

**To Reproduce**:
1. Log in 
2. Add product to cart
3. Open cart
4. Enter coupon for free shipping (Coupon code: FREE)

**Actual result**:
The estimated shipping price doesn't change in the cart and shipping step
![image](https://user-images.githubusercontent.com/73526235/104321605-84164880-54ec-11eb-907d-10fc0428d366.png)

**Comment by zans-laksa** [comment]
There are two ways how coupon is affecting shipping.
1. When coupon is applied, free shipping delivery method is displayed on the checkout shipping page.
https://docs.magento.com/user-guide/marketing/price-rules-cart-free-shipping.html
2. Selected shipping method gets discount.
https://community.magento.com/t5/Magento-2-x-Admin-Configuration/50-Off-Shipping-Rule/m-p/126798/highlight/true#M3861

We are not calculating cart totals.
Thus for the second case cart totals are updated according to magento cart logic.

We don't update the shipping price / grand total on delivery method change.
And since we don't have ability to select a delivery method on the cart page, we still see same estimated shipping price after coupon is applied.

So i've added ability to reload delivery method list on coupon changes on the checkout shipping step.
Then i've talked to @lianastaskevica and we decided to remove coupon component from the shipping page, since it't not present on the magento luma's shipping page too.
