### ISSUE TITLE
'Error fetching URL-rewrites' appears if user opened specific product

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2096]
**Description**:
'Error fetching URL-rewrites' appears if user opened specific product

**Expected behavior**:
Errors are missing

**To Reproduce**:
1. Open product page - https://master.d25kd40decjpue.amplifyapp.com/default/n-comma-casual-identity-quilted-jacket.html
https://master.d25kd40decjpue.amplifyapp.com/default/product-y.html
https://master.d25kd40decjpue.amplifyapp.com/default/qwerty.html
https://master.d25kd40decjpue.amplifyapp.com/default/n-dark-grey-chino.html

**Actual result**:
Error message ''Error fetching URL-rewrites' appears ' appears
Errors appear in the console
https://drive.google.com/file/d/1Cb13rkb4mJLPwHH5h7jqF1Uaxavbw_GX/view?usp=sharing
![image](https://user-images.githubusercontent.com/73526235/104688761-fca62080-5709-11eb-8e7a-ccfcc133a052.png)

**Comment by arangaw** [comment]
All this is wrong fix. Hiding exception is not good. The actual issue happens due to wrong class used to check the item stock.

$isInStock = $this->stockItemRepository->get($id)->getIsInStock();

you are trying to get the stock using product id but it actually checks the item_id of cataloginventory_stock_item. If the cataloginventory_stock_item item_id is changed due to some reason you can get this exception.

please use $isInStock = $this->stockRegistry->getStockItem($id)->getIsInStock(); instead of above. It actually checks the stock against product id.

`` <?php
/**
 * @category  ScandiPWA
 * @package   ScandiPWA\UrlrewriteGraphQl
 * @author    Vladimirs Mihnovics <info@scandiweb.com>
 * @copyright Copyright (c) 2019 Scandiweb, Ltd (http://scandiweb.com)
 * @license   OSL-3.0
 */
declare(strict_types=1);

namespace ScandiPWA\UrlrewriteGraphQl\Model\Resolver;

use Magento\Catalog\Model\Product\Attribute\Source\Status;
use Magento\Catalog\Model\ResourceModel\Product\CollectionFactory;
use Magento\CatalogInventory\Api\StockRegistryInterface\Proxy;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\Exception\NoSuchEntityException;
use Magento\Framework\GraphQl\Exception\GraphQlInputException;
use Magento\Framework\GraphQl\Schema\Type\ResolveInfo;
use Magento\Framework\GraphQl\Config\Element\Field;
use Magento\Framework\GraphQl\Query\ResolverInterface;
use Magento\Store\Model\StoreManagerInterface;
use Magento\UrlRewrite\Model\UrlFinderInterface;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
use Magento\UrlRewriteGraphQl\Model\Resolver\UrlRewrite\CustomUrlLocatorInterface;
use Magento\Catalog\Api\CategoryRepositoryInterface;
use Magento\CatalogInventory\Model\Stock\StockItemRepository;
use Magento\Store\Model\ScopeInterface;

/**
 * UrlRewrite field resolver, used for GraphQL request processing.
 */
class EntityUrl implements ResolverInterface
{
    /**
     * Config key 'Display Out of Stock Products'
     */
    const XML_PATH_CATALOGINVENTORY_SHOW_OUT_OF_STOCK = 'cataloginventory/options/show_out_of_stock';

    /**
     * @var UrlFinderInterface
     */
    private $urlFinder;

    /**
     * @var StoreManagerInterface
     */
    private $storeManager;

    /**
     * @var CustomUrlLocatorInterface
     */
    private $customUrlLocator;

    /**
     * @var CollectionFactory
     */
    private $productCollectionFactory;

    /**
     * @var CategoryRepositoryInterface
     */
    private $categoryRepository;

    /**
     * @var StockItemRepository
     */
    private $stockItemRepository;

    /**
     * @var ScopeConfigInterface
     */
    private $scopeConfig;

    /**
     * @var Proxy
     */
    private $stockRegistry;

    /**
     * @param UrlFinderInterface $urlFinder
     * @param StoreManagerInterface $storeManager
     * @param CustomUrlLocatorInterface $customUrlLocator
     * @param CollectionFactory $productCollectionFactory
     * @param CategoryRepositoryInterface $categoryRepository
     * @param StockItemRepository $stockItemRepository
     * @param ScopeConfigInterface $scopeConfig
     */
    public function __construct(
        UrlFinderInterface $urlFinder,
        StoreManagerInterface $storeManager,
        CustomUrlLocatorInterface $customUrlLocator,
        CollectionFactory $productCollectionFactory,
        CategoryRepositoryInterface $categoryRepository,
        StockItemRepository $stockItemRepository,
        ScopeConfigInterface $scopeConfig,
        Proxy $stockRegistry
    ) {
        $this->urlFinder = $urlFinder;
        $this->storeManager = $storeManager;
        $this->customUrlLocator = $customUrlLocator;
        $this->productCollectionFactory = $productCollectionFactory;
        $this->categoryRepository = $categoryRepository;
        $this->stockItemRepository = $stockItemRepository;
        $this->scopeConfig = $scopeConfig;
        $this->stockRegistry = $stockRegistry;
    }

    /**
     * @inheritdoc
     */
    public function resolve(
        Field $field,
        $context,
        ResolveInfo $info,
        array $value = null,
        array $args = null
    ) {
        if (!isset($args['url']) || empty(trim($args['url']))) {
            throw new GraphQlInputException(__('"url" argument should be specified and not empty'));
        }

        $result = null;
        $url = $args['url'];

        if (substr($url, 0, 1) === '/' && $url !== '/') {
            $url = ltrim($url, '/');
        }

        $customUrl = $this->customUrlLocator->locateUrl($url);
        $url = $customUrl ?: $url;
        $urlRewrite = $this->findCanonicalUrl($url);

        if ($urlRewrite) {
            $id = $urlRewrite->getEntityId();
            $type = $this->sanitizeType($urlRewrite->getEntityType());

            $result = [
                'id' => $id,
                'type' => $type,
                'canonical_url' => $urlRewrite->getTargetPath(),
            ];

            if ($type === 'PRODUCT') {
                // Using this instead of factory due https://github.com/magento/magento2/issues/12278
                $collection = $this->productCollectionFactory->create()
                    ->addAttributeToFilter('status', ['eq' => Status::STATUS_ENABLED]);
                $product = $collection->addIdFilter($id)->getFirstItem();

                $isInStock = $this->stockRegistry->getStockItem($id)->getIsInStock();

                $isInStock = $this->stockItemRepository->get($id)->getIsInStock();

                $isOutOfStockDisplay = $this->scopeConfig->getValue(
                    self::XML_PATH_CATALOGINVENTORY_SHOW_OUT_OF_STOCK,
                    ScopeInterface::SCOPE_STORE
                );

                /*
                 * return 404 page if product has no data
                 * or out of stock product display is disabled
                 */
                if (!$product->hasData() || !$isOutOfStockDisplay && !$isInStock) {
                    return null;
                }

                $result['sku'] = $product->getSku();
            } elseif ($type === 'CATEGORY') {
                $storeId = $this->storeManager->getStore()->getId();
                $category = $this->categoryRepository->get($id, $storeId);

                if (!$category->getIsActive()) {
                    return null;
                }
            }
        }

        return $result;
    }

    /**
     * Find the canonical url passing through all redirects if any
     *
     * @param string $requestPath
     * @return UrlRewrite|null
     */
    private function findCanonicalUrl(string $requestPath) : ?UrlRewrite
    {
        $urlRewrite = $this->findUrlFromRequestPath($requestPath);
        if ($urlRewrite && $urlRewrite->getRedirectType() > 0) {
            while ($urlRewrite && $urlRewrite->getRedirectType() > 0) {
                $urlRewrite = $this->findUrlFromRequestPath($urlRewrite->getTargetPath());
            }
        }
        if (!$urlRewrite) {
            $urlRewrite = $this->findUrlFromTargetPath($requestPath);
        }

        return $urlRewrite;
    }

    /**
     * Find a url from a request url on the current store
     *
     * @param string $requestPath
     * @return UrlRewrite|null
     * @throws NoSuchEntityException
     */
    private function findUrlFromRequestPath(string $requestPath) : ?UrlRewrite
    {
        return $this->urlFinder->findOneByData(
            [
                'request_path' => $requestPath,
                'store_id' => $this->storeManager->getStore()->getId()
            ]
        );
    }

    /**
     * Find a url from a target url on the current store
     *
     * @param string $targetPath
     * @return UrlRewrite|null
     * @throws NoSuchEntityException
     */
    private function findUrlFromTargetPath(string $targetPath) : ?UrlRewrite
    {
        return $this->urlFinder->findOneByData(
            [
                'target_path' => $targetPath,
                'store_id' => $this->storeManager->getStore()->getId()
            ]
        );
    }

    /**
     * Sanitize the type to fit schema specifications
     *
     * @param string $type
     * @return string
     */
    private function sanitizeType(string $type) : string
    {
        return strtoupper(str_replace('-', '_', $type));
    }
}
``

**Comment by winniepukki** [comment]
@arangaw @lianastaskevica 

[StockRegistryInterface Interface](https://www.magentoextensions.org/documentation/interface_magento_1_1_catalog_inventory_1_1_api_1_1_stock_registry_interface.html) was deprecated with Magento 2.3.0. Referencing the official message:
`
Deprecated:
2.3.0 Replaced with Multi Source Inventory https://devdocs.magento.com/guides/v2.3/inventory/catalog-inventory-replacements.html
`

The only way to avoid issue is to use [following services](https://devdocs.magento.com/guides/v2.4/inventory/inventory-api-reference.html#inventory-management-api) that reside under the `Magento/InventoryApi/Api` namespace, replacing deprecated services and APIs. Since the error has been fixed on the fly, the `inventory-management-api` implementation is in process. Appreciate your time and effort!

**Comment by arangaw** [comment]
Thanks @winniepukki for the update.

**Comment by surelockrich** [comment]
> @arangaw @lianastaskevica
> 
> [StockRegistryInterface Interface](https://www.magentoextensions.org/documentation/interface_magento_1_1_catalog_inventory_1_1_api_1_1_stock_registry_interface.html) was deprecated with Magento 2.3.0. Referencing the official message:
> `Deprecated: 2.3.0 Replaced with Multi Source Inventory https://devdocs.magento.com/guides/v2.3/inventory/catalog-inventory-replacements.html`
> 
> The only way to avoid issue is to use [following services](https://devdocs.magento.com/guides/v2.4/inventory/inventory-api-reference.html#inventory-management-api) that reside under the `Magento/InventoryApi/Api` namespace, replacing deprecated services and APIs. Since the error has been fixed on the fly, the `inventory-management-api` implementation is in process. Appreciate your time and effort!

@winniepukki Can you explain to us in bit details how to solve this issue it will be very helpful for us
