### ISSUE TITLE
Menu Manager doesn't allow to upload svg

### ISSUE THREAD

**Issue by aleksejtsebinoga** [scandipwa/scandipwa#2136]
**Description**:
What is wrong? What happened?

**Expected behavior**:
Item with SVG is saved.

**Screenshots, Video, Logs**
https://www.awesomescreenshot.com/video/2550432?key=14aef2fdbaf452cf1318a3ba298d65e7

**To Reproduce**:
Go to the menu Menu Manager in admin and open menu you want to edit;
Create new item;
Upload svg;
Save;
Items is saved.

**Versions**:
All versions affected.

**Comment by winniepukki** [comment]
According to the [Magento 2.0.16 and 2.1.9 Security Update](https://magento.com/security/patches/magento-2.0.16-and-2.1.9-security-update), there is no further SVG file extension support in default Magento, since SVGs may result `APPSEC-1673: Stored xss using svg images in Favicon`. Please find the screenshot attached as an evidence that there is no SVG support for `Category images` either.

![image](https://user-images.githubusercontent.com/43637240/109506536-69049580-7aa6-11eb-8e07-654dd1a7ef28.png)
