### ISSUE TITLE
Products are missing in wishlist for one user

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2197]
**Description**:
Products are missing in the wishlist for one user

**Expected behavior**:
Product is displayed in wishlist

**To Reproduce**:
1. Log in (new@new.new/ Scandipwa123)
2. Open some product page
3. Add this product to wishlist

**Actual result**:
debugMessage: "Call to a member function getValue() on null" in network
Wishlist is empty

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2240 + https://github.com/scandipwa/wishlist-graphql/pull/12

To reproduce:

1. Switch to UK store (or any other using Luma), open configurable product, add to wishlist without selecting required options
2. Switch back to ScandiPWA storefront, open wishlist

Result: wishlist is not loaded. Failure in processing GraphQL request
Expected: wishlist is loaded

**Comment by aleksandrakorolova** [comment]
Still, products are missing in wishlist
New error appears in network when adding product to wishlist:
debugMessage: "Notice: Undefined offset: 2765 in /var/www/public/vendor/scandipwa/wishlist-graphql/src/Model/Resolver/WishlistItemsResolver.php on line 139"

**Comment by tatiana-scandi** [comment]
This is another issue not related to the previous one (the previous one is fixed, but the new@new.new user has 32 more items in wishlist... :grinning:).
The issue is with the following product: https://master.d25kd40decjpue.amplifyapp.com/default/qwerty.html (I made a user wishlist data backup and removed wishlist items one by one until the wishlist began to load). Yet I was unable to reproduce the issue for this very product again (tried to add to wishlist from catalog page and product page, tried to add to wishlist and set product `Out of stock`, etc.). Issue needs to be reproduced at least one more time to gather more information on the bug and to confirm that the issue is real and not just one time breakdown that happened 2 months ago. If not, I suppose the issue can be closed.
