### ISSUE TITLE
Magento 2.4.2 support

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#2244]
**Description**:
We need to create support for Magento 2.4.2. See the release notes here https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-2.html

**Comment by zans-laksa** [comment]
1. Before upgrade there should be installed and enabled two php extensions: `libsodium` and `fileinfo`.
2. In order to start / stop project `magento scripts` should have a configuration file for the magento 2.4.2.
3. Fixed slider upload.
4. Fixed braintree eslint issues.
5. Fixed braintree vault eslint and reducer inject issue.
6. Fixed theme issues found after update.

What is left:
1. Magento has implemented compare products graphql support. Now comparison lists should be created before the products are added to comparison. This is marked as the breaking changes in the changelog, but our current implementation still works. This should be fixed later in a separate task.
2. If a child of a configurable product is set to another store, default magento still shows it's options on the category filters, but hides on the product page. In our current implementation these options are visible, but disabled. This doesn't break anything and should be fixed later in a separate task.

**Comment by lianastaskevica** [comment]
Issues are created:
1. https://github.com/scandipwa/scandipwa/issues/2374
2. https://github.com/scandipwa/scandipwa/issues/2375
