### ISSUE TITLE
Price is missing for bundle product in Wishlist

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2448]
**Description**:
Price is missing for bundle product in Wishlist

**Expected behavior**:
Price is displayed

**To Reproduce**:
1. Log in
2. Open bundle product
3. Add to Wishlist
4. Open Wishlist

**Actual result**:
Price is missing
![image](https://user-images.githubusercontent.com/73526235/113698007-ac24da80-96dc-11eb-9035-205026a6914d.png)

**Comment by almaVitola** [comment]
I was working on this bug and I managed to display the bundle price by removing the stock status check for bundle product in ProductCard.component.js. But the displayed price was the min bundle item price no matter what options have been chosen.
**Reason: Chosen options are not added to the wishlist but the whole bundle.** And because the bundle itself does not have a stock status it does not pass the stock status check and the price is not displayed. And if I disable the stock status check we get min price also because the options were not added.

**Comment by aleksandrakorolova** [comment]
Closed because price is displayed
![Screenshot 2021-09-02 at 14 23 48](https://user-images.githubusercontent.com/73526235/131835785-bcebb614-9c2a-4d39-b48a-232012177bb5.png)
Created separate task #3252
