### ISSUE TITLE
Checkout - BE Address Number is displayed instead of the Address name on the FE

### ISSUE THREAD

**Issue by KrissOerts** [scandipwa/scandipwa#2452]
**Description**:
The BE Address number is displayed in the checkout Shipping step instead of the Address name that is displayed in the User Account "Address Book" tab.

**Expected behavior**:
The Address number displayed in the Checkout Shipping step matches the Address Number in the User Account "Address Book" tab.

**Screenshots, Video, Logs**:
![image](https://user-images.githubusercontent.com/77437826/113779138-e8385980-9735-11eb-9d05-31fa07a05e2b.png)
![image](https://user-images.githubusercontent.com/77437826/113779177-f7b7a280-9735-11eb-8da7-793819799736.png)

**To Reproduce**:
1. Open [https://tech-demo.scandipwa.com/](url)
2. Log into the FE user account.
3. Navigate to the “Address book” tab in the user Account.
4. Add a Billing and a Shipping address.
5. Observe the Address Nr.
5. Go to any PLP and add any Product to the cart.
6. Click on the “Cart” icon in the header.
7. Click on "Secure Checkout".
8. Observe the Address Nr.

**Additional context**:
Issue found on Whey-Protein and is replicable on the ScandiPWA demo.
[https://scandiflow.atlassian.net/browse/WHEY-726](url)

**Comment by aleksandrakorolova** [comment]
Closed task because can't reproduce. You can check it on https://40kskudemo.scandipwa.com/default/
![Screenshot 2021-08-30 at 16 45 26](https://user-images.githubusercontent.com/73526235/131349188-4284e56e-9f7e-43de-b942-87208d9c8efc.png)
![Screenshot 2021-08-30 at 16 45 14](https://user-images.githubusercontent.com/73526235/131349200-57718540-75bc-4026-8d4f-f94c9e93a863.png)
