### ISSUE TITLE
Translate "Price" & "Category" in Category Overly Filter

### ISSUE THREAD

**Issue by uandiweb** [scandipwa/scandipwa#2562]
**Description**:
I was able to translate anything I needed using the translation file. However, I was not able to translate the words "Price" & "Category" in the category overly filter.

**Expected behavior**:
Translating the the words "Price" & "Category" in the translation file should replace the words in the front end.

**Screenshots, Video, Logs**
<img width="418" alt="filter" src="https://user-images.githubusercontent.com/20729592/116434189-33ff8f80-a818-11eb-8fdf-98f7250eed95.png">

**To Reproduce**:
1. Add the word "Price" (and/or "PRICE" and/or "price") to the translation file, and translate it to a different word. No change will take place in the front end.
2. Add the word "Category" (and/or "CATEGORY" and/or "category") to the translation file, and translate it to a different word. No change will take place in the front end.

**Versions**:
- ScandiPWA: 4.x

**Comment by tatiana-scandi** [comment]
Actually frontend files with translations should not be used for translating instances like attribute names. What should be used is multistore setup + setting different labels for different languages:
<img width="1330" alt="price : Product Attributes : Attributes : Stores : Pre Magento Admin Suff 2021-07-22 17-42-02" src="https://user-images.githubusercontent.com/79456428/126676720-380fef2b-397c-4db4-80d2-10b4cf635ed5.png">

Or setting the default label using the language you need (this option will work only, if you need one language):
<img width="1311" alt="price : Product Attributes : Attributes : Stores : Pre Magento Admin Suff 2021-07-22 17-45-26" src="https://user-images.githubusercontent.com/79456428/126676893-f091d369-0c4e-4fee-b944-d2c4ff546f5b.png">

This should work from scratch, but the problem is that there is a bug in `magento-catalog-graphql` module related to `price` and `category` attributes, which hasn't been fixed yet. `price` and `category` are special attributes and handled using logic different from the other attributes, this is why other attributes have correct translations.
https://github.com/magento/magento2/issues/27657#issuecomment-791436235

So order to fix this issue, adding custom logic for 2 attributes was required:
https://github.com/scandipwa/catalog-graphql/pull/111
