### ISSUE TITLE
Add support to the Pagination Frame Skip

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#2791]
**Description**:
Please add support to the Pagination Frame Skip (PFS) as it works in the Luma theme. This means that when the PFS is set to 2 or more, the user will see "..." and the numbers of the first and last pages.

It can be tested with this page: https://scandipwapmrev.indvp.com/demo/women.html

**Steps to change the configuration in the admin panel:**
1. Open Admin panel > go to Content > Design > Configuration
2. Open Design Configuration in edit mode for the desired Store View 
2. Open Pagination section
3. Define a number for the Pagination Frame field
4. Define a number for  the Pagination Frame Skip field
5. Tap 'Save' > Flush Cache Storage

**How it works**:

- If the Pagination Frame Skip (PFS) is null, 0 or 1, there is no … and it doesn’t show the first and last numbers (1 and 14 in the example). 
- If the PFS is equal or greater than 2, we’ll have `1 … PF numbers … 14`.
- Supposing you have PF = 3, PFS = 2 and you are on page 7, it looks like: `1 … 6 7 8 … 14`
  - If you click on the … to the right, you’ll go to page 10 (8+2). 
  - If you click in the … to the left you’ll go to page 4 (6-2).
- If you are in a situation where the sum would be 1 or less or 14 or more, it takes you to the second or penultimate page (respectively). Eg: `1 … 10 11 12 … 14`. Click on … to the right and you’ll be taken to page 13.

**Screenshot**

Here the PF and PFS are set to 3.
![image](https://user-images.githubusercontent.com/82165392/122397423-562ba900-cf4f-11eb-97d9-0ea35c59e180.png)

If we click on the ... to the right, we're taken to page 10 (7+3)
![image](https://user-images.githubusercontent.com/82165392/122397793-adca1480-cf4f-11eb-817b-8316957b1054.png)

**Comment by tatiana-scandi** [comment]
The logic I implemented is explained below. It is not a 100% match to Luma's logic, I tried to make it a bit more logical and user friendly, while keeping the most important points:


PFS is null, 0 or 1:
- behaves as before (so, you don't know how many pages are after current pages set)
- `...` are not shown
- links to first and last pages are not shown
- total number of pages corresponds to PF
- active page position is centered

PFS is > 1:
- `...` is displayed each time there is a gap between first page and first page in pagination frame (or last page in pagination frame and last page)
E.g.
`1 2 3 4  ... 7`
`1 ... 3 4 5 ... 7`
`1 ... 4 5 6 7`

- first and last page links are always displayed (in order to make the behavior more consistent - there is difference in behavior with Luma).
- first  `...` lead to page number calculated as "first page in PF - PFS". E.g. we have `1 ... 5 6 7 ... 14` and PRS = 2. First `...` will lead to page 5 - 2 = 3. Same logic for second `...`.
-  First `...` will never lead you to a page number less than 2. Second `...` will never lead you to a page number greater than last page number minus 1 (penultimate page).
- active page position is centered

Previous page link is hidden when:
- active page is the first page
- all pages are already displayed

Next page link is hidden when:
- active page is the last page
- all pages are already displayed

**Comment by Elena-Evsa** [comment]
Actual result: 
1. 3 dots are not appeared if PFS=2 and more
2. Active page position is not centered
![image](https://user-images.githubusercontent.com/84388061/123593704-813bb580-d7f7-11eb-8357-da319d1f06d8.png)
