### ISSUE TITLE
Stock status 'Null' is received in graphql but on FE - in stock status if product qty is set to 0 in Admin panel

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2796]
**Description**
Stock status 'Null' is received in graphql but on FE - in stock status if product qty is set to 0 in Admin panel

**Expected behavior**:
Out of stock is displayed as in default Magento
![Screenshot 2021-06-18 at 09 59 54](https://user-images.githubusercontent.com/73526235/122520173-f3541380-d01b-11eb-805a-3e4f3d391d5c.png)

**To Reproduce**:
1. Open product which status set in stock but qty - 0
2. Notice to product status
3. Open network and check stock status

**Actual result:**:
In stock status is displayed on FE
Stock status 'Null' is received in graphql
![Screenshot 2021-06-18 at 09 58 30](https://user-images.githubusercontent.com/73526235/122519979-c30c7500-d01b-11eb-9c64-f7a788942eea.png)

**Additional context**:
https://master.d25kd40decjpue.amplifyapp.com/default/women/n-black-chino-7

**Comment by riha112** [comment]
Stock status for config product parent will always be null _([example](https://master.d25kd40decjpue.amplifyapp.com/default/women/women-dresses/iphone-12.html), product is in stock, but parent is null and variants are in stock),_ instead child/variant products should be looked at.

This issue was resolved by issue:
* #2848 
* #2842 
* #2734

**Comment by aleksandrakorolova** [comment]
Created separate tasks - #3122 and #3123
