### ISSUE TITLE
Ooops page when opening Downloadable product with separately links and customization options

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2847]
**Description**:
Ooops page when opening Downloadable product with separately links and customization options

**Expected behavior**:
PDP opens 

**To Reproduce**:
1. Open Downloadable product with separately links and customization options - https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/downloadable-product-1.html

**Actual result**:
Ooops page opens
![Screenshot 2021-07-06 at 09 10 59](https://user-images.githubusercontent.com/73526235/124551262-8bcefe00-de3a-11eb-8146-bee943fd1460.png)

**Comment by carinadues** [comment]
Tested with 2 downloadable products with separate links and customizable options, both open all right.
https://5-0-0-rc.d25kd40decjpue.amplifyapp.com/default/downloadable-card-gold.html 
https://5-0-0-rc.d25kd40decjpue.amplifyapp.com/default/kids/downloadable-product-1.html

The issue was fixed with PR https://github.com/scandipwa/scandipwa/pull/3020
