### ISSUE TITLE
Store home page URL sets Menu Tab to bottom navigation state if 1. no trailing slash 2. empty cache

### ISSUE THREAD

**Issue by tatiana-scandi** [scandipwa/scandipwa#2856]
Issue 1:
To reproduce: 
1. Open mobile layout
2. Go to http://scandipwapmrev.indvp.com/default (no slash at the end)

**Result:** MENU TAB (second tab) is marked as active in bottom navigation state
**Expected result:** HOME TAB (first tab) is marked as active in bottom navigation state

Issue 2:
To reproduce: 
1. Open mobile layout in incognito tab
2. Go to http://scandipwapmrev.indvp.com/default/ 

**Result:** MENU TAB (second tab) is marked as active in bottom navigation state
**Expected result:** HOME TAB (first tab) is marked as active in bottom navigation state

**Comment by tatiana-scandi** [comment]
@Elena-Evsa please, retest everything related to navigation (top navigation state, bottom navigation state, redirecting to other pages via buttons, going to pages via direct urls, back button navigation, mulitstore setup, etc.)

**Comment by Elena-Evsa** [comment]
This issue is fixed on Amplify web preview

Retest everything related to navigation
1. Loaded URLs of PDP, PLP, CMS, Home, Login, Create, Forgot password, Compare, Confirm pages with slash and without on mobile and desktop - OK
2. Went through categories in top navigation bar on desktop - OK
3. Went through categories in bottom navigation bar on mobile, added slash to URLs and loaded them - OK
4. Tap on button on pages - found 1 issue
8. Tap on Back button on page and phone Back button - found 1 issue
9. Loaded URLs: Target Path, Request path, with and without slash - OK
10. Went through categories in Breadcrumbs
11. Multistore setup - can check only on PMREV

**Comment by aleksandrakorolova** [comment]
Created separate task - #2919

**Comment by aleksandrakorolova** [comment]
@tatiana-scandi looks like the menu tab is painted over if user opens the homepage without slash in incognito mood (or clear browser cache)
![Screenshot 2021-07-20 at 15 12 16](https://user-images.githubusercontent.com/73526235/126321999-10821d65-1032-4643-b7e8-3c703393066e.png)

**Comment by tatiana-scandi** [comment]
Fix for the latest issue: https://github.com/scandipwa/scandipwa/pull/2978

No full retest is required, please, check just cases with incognito tab and `/default`, `/default/` and `/` after hostname.

**Comment by Elena-Evsa** [comment]
Shipping step and billing step page shows Menu button - should be Cart

**Comment by tatiana-scandi** [comment]
I created a separate issue, as this is another bug: https://github.com/scandipwa/scandipwa/issues/3006
