### ISSUE TITLE
Strange attribute 'shoes_size_bucket' is displayed without options in Layered Navigation

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2893]
**Description**:
Strange attribute 'shoes_size_bucket' is displayed in Layered Navigation

**Expected behavior**:
Strange attribute 'shoes_size_bucket' is missing in Layered Navigation

**To Reproduce**:
1. Open accessories category - https://master.d25kd40decjpue.amplifyapp.com/default/accessories.html

**Actual result**:
Strange attribute 'shoes_size_bucket' is displayed without options in Layered Navigation
![Screenshot 2021-07-14 at 14 27 57](https://user-images.githubusercontent.com/73526235/125615933-a29d988c-c408-4141-a27a-45adc47d18d0.png)

**Additional context**:
This attribute doesn't have options after #2649

**Comment by tatiana-scandi** [comment]
I found out that the issue was with `shoes_size` attribute being incorrectly save for 2 configurations of the following product: https://master.d25kd40decjpue.amplifyapp.com/default/accessories/28-1-configurable-product.html
I don't see the issue in category https://master.d25kd40decjpue.amplifyapp.com/default/accessories.html any more.

@aleksandrakorolova please, recheck if the issue is still reproduced for any other categories.

**Comment by carinadues** [comment]
Couldn't reproduce the issue for other categories. 
Checked the following categories: Kids, Accessories, Tech, Women, Men, Jeans, Jackets, Shoes, Trousers, Boys Jeans, Bags, E-book, Phone, Caps and Hats.

**Comment by aleksandrakorolova** [comment]
@tatiana-scandi I found one more strange attribute **color_bucked**
https://master.d25kd40decjpue.amplifyapp.com/default/kids/jeans/girls-jeans.html
https://master.d25kd40decjpue.amplifyapp.com/default/accessories/accessories-bags/travel-bags.html

**Comment by tatiana-scandi** [comment]
Weird, but same as here in the comment to this issue: 
https://github.com/scandipwa/scandipwa/issues/2906
you need to:
1. rebuild indexes
```sudo docker exec -ti staging_app_1 /bin/bash
magento indexer:reindex```
2. clear magento cache

It will recalculate attributes names.

**Comment by tatiana-scandi** [comment]
Just wanted to provide a bit more details regarding why issues like these are happening.

In order to improve performance of aggregations in filters, Elasticsearch is being used. Process includes two steps:
1. Perform request to Elasticsearch to get buckets with aggregations and product IDs
2. Data from step 1 is being enriched with data from magento SQL DB

Approach above works well if correct data in present in Elasticsearch. Data in Elasticsearch is updated in two cases:
1. When customer updates product in magento admin (in this case product is re-indexed automatically)
2. When you run reindex explicitly (by logging in to magento server and running `magento indexer:reindex`)

Normally, option 2 should never be used. But I needed to do run it, because somebody removed attribute (or attribute value) without checking that it's being used by any product. Magento doesn't perform deep checks and leaves references to removed attribute (or it's value) in the relevant tables. This bad data is being indexed by Elasticsearch and later is returned in the buckets.
But as attribute was already removed from the table with attributes, there is no way for Magento to properly populate attribute title or color (such details exist only in DB). In Magento docs there is a recommendation to perform following before removing attribute or it's value ([link](https://docs.magento.com/user-guide/stores/attribute-delete.html)):
```
Before deleting an attribute, make sure that it is not currently used by any product in your catalog. An easy way to determine if an attribute is in use is to use the Export tool to check the list of product Entity Attributes. If the attribute is not included in the list, then it is not used by any products in the catalog.
```

Below I'd like to describe example, which I fixed today. Somebody selected one of the `Color` attribute values as default and later removed it without checking for references). This color was already assigned to group of products + magento didn't remove this value from `default_value` column in the `eav_attribute` table. You can see that attribute value assignment wasn't removed by inspecting table `catalog_product_entity_int`:
![image](https://user-images.githubusercontent.com/79456428/127302391-15a9363b-5cf7-46f4-b96f-95593c05f980.png)

These bad references were indexed by Elasticsearch and counted in the bucket:
![image](https://user-images.githubusercontent.com/79456428/127303021-038b5634-e747-4da2-95da-ed595459bbbc.png)

I fixed issue by setting `Color` as `NULL` for all products, which referenced removed color, using SQL below:
```
UPDATE magento.catalog_product_entity_int
SET value=NULL
WHERE attribute_id=93 AND value='5584';
```

After that I reindexed data one more time and bad attribute disappeared from filters.

**So, the issue is happening deep inside Magento logic and the problem is that references are not being updated as they should be. So you need to override how Magento admin works when removing attributes, modify SQL requests being executed (it even doesn't fit into any of our `*-graphql` modules). There is no easy way to fix such an issue. I propose just to follow official recommendations and not to delete attribute values linked to some products.**
