### ISSUE TITLE
PLP is broken when refreshing page or returning back to PLP

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2896]
**Description**:
Page is broken. All content (products, category information) is displayed on the left side instead Layered navigation

**Expected behavior**:
Page looks well
![Screenshot 2021-07-15 at 08 04 51](https://user-images.githubusercontent.com/73526235/125731712-dbeeef31-e5d1-4e5d-8585-e64e6a2259e0.png)

**To Reproduce 1**:
1. Open PLP
2. Refresh page

**To Reproduce 2**:
1. Open PLP
2. Select open some product
3. Return back to PLP

**Actual result**:
Page is broken. All content (products, category information) is displayed on the left side instead Layered navigation
![Screenshot 2021-07-15 at 08 02 46](https://user-images.githubusercontent.com/73526235/125731958-ccbe9ba3-52f7-4bbc-b7f2-5d78fb256d50.png)

**Additional context**:
https://drive.google.com/file/d/1j-zfdzxTrExr5qteU7am-81Oy_k-wEBW/view?usp=sharing
Helps only clear cache in browser

**Comment by zans-laksa** [comment]
Some components there are split in chunks and lazy-loaded.
These components can reuse same shared components. In that case each chunk contains shared component styles.
Since  chunks are loaded on demand, the later loaded component injects it's styles and we cannot control the order of css files.
This results that last loaded component can override the styles of previous loaded components.

For example:
```
// category chunk
.Overlay { ... }
.CategoryFilterOverlay { /* overrides .Overlay styles for CategoryFilterOverlay component */ }

// account chunk
.Overlay { /*
  has same properties as .Overlay in category chunk.
  but since this is loaded later and has same specificity as .CategoryFilterOverlay,
  it overrides .CategoryFilterOverlay styles
*/ }
```

But the most anoying that this can happen to any component in any chunk. Not just for filters on PLP.

**Comment by aleksandrakorolova** [comment]
Can reproduce with these steps:
1. Open PLP
2. Open PDP
3. Return to/Open PLP
https://drive.google.com/file/d/10zmokeVBaddjz2Y0Ry5NquhrpKTiZP41/view?usp=sharing

**Comment by carinadues** [comment]
Tested in Chrome and Opera (in windows). All good.
