### ISSUE TITLE
Product count is displayed including out of stock product in Layered Navigation 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2906]
**Description**:
Product count is displayed including out of stock product in Layered Navigation 

**Expected behavior**:
Product count is displayed excluding out of stock product (in this case 50)

**To Reproduce**:
1. Open Admin panel -> Go to Stores -> Configuration -> Catalog -> Inventory
2. Set Display Out of Stock Products to no
3. Save
4. Clear Cache
5. Open PLP where should be out of stock products - https://master.d25kd40decjpue.amplifyapp.com/default/women
6. Select price filter - From US$0.00, to US$38.99 (97)

**Actual result**:
Product count is displayed including out of stock product- 97
Product count is displayed excluding out of stock product- 50
![Screenshot 2021-07-15 at 12 17 29](https://user-images.githubusercontent.com/73526235/125764363-47139a69-b6ab-434e-8f44-c8c528c839b1.png)

**Comment by tatiana-scandi** [comment]
Number of products for each category is stored in ElasticSearch. When `Display Out of Stock Products` setting is being changed, product numbers should chnage after indexes are updated. But indexes are not updated for some reason:
(you see "Reindex is required")
![Index Management : Tools : System : Pre Magento Admin Suff 2021-07-15 16-28-50](https://user-images.githubusercontent.com/79456428/125816323-a2b318d8-0322-4631-9ecb-aaec603d9583.png)

In order to update indexes manually, you need to SSH to the server and execute:
```
sudo docker exec -ti staging_app_1 /bin/bash
magento indexer:reindex
```

After that number of products is updated to correct values.
