### ISSUE TITLE
Layered Navigation is missing for a specific category

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#2911]
**Description**:
The filters (Layered Navigation) are missing in the Man Knitwear category PLP.

**Expected behavior**:
![image](https://user-images.githubusercontent.com/82165392/125970440-13917460-0684-4a88-bfd0-2381e162013b.png)

**Actual result**
![image](https://user-images.githubusercontent.com/82165392/125970183-5e000962-6007-4f18-a488-99b0a06803b2.png)

**To Reproduce**:
Open https://master.d25kd40decjpue.amplifyapp.com/default/men/tops/man-knitwear.html

**Comment by aleksandrakorolova** [comment]
Closed this task because it's not bug. It's expected if we set Anchor to No for this category
Here you can see layered navigation for knitwear category if Anchor is set to Yes
![Screenshot 2021-07-19 at 08 00 40](https://user-images.githubusercontent.com/73526235/126105526-336f20bf-17f9-4c95-94a3-3d672a1393e6.png)
