### ISSUE TITLE
Ooops page opens when clicking on logo on PDP

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2925]
**Description**:
Ooops page opens when clicking on logo on PDP

**Expected behavior**:
No errors. Homepage opens 

**To Reproduce**:
1. Open Homepage
2. Scroll down to the widget
3. Open some product
4. Click on Logo

**Actual result**:
Ooops page opens
![Screenshot 2021-07-20 at 08 01 04](https://user-images.githubusercontent.com/73526235/126264833-6e7a3b83-0b7f-4e32-bac0-1c0e23b182df.png)

**Comment by tatiana-scandi** [comment]
More correct steps to reproduce would be:
1. Open configurable product (as a result of this action product is added to recently viewed products and its primary info is stored in localstorage)
2. Open homepage (via logo click or not doesn't matter)

Why problem appears: such data as product variants is not stored in localstorage, some time is needed for secondary product data to be requested from the server. Error `Cannot read property filter of undefined` appears due to variants being undefined during this time. So I'm just setting default value of variants to empty array to avoid errors while data is loading. 

Fix: https://github.com/scandipwa/scandipwa/pull/2949
