### ISSUE TITLE
Blank page is displayed on FE if Locale is set not English (US)

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3100]
**Description**:
Blank page is displayed on FE if Locale is set not English (US)

**Expected behavior**:
No errors
Website works correctly

**To Reproduce**:
1. Open Admin panel -> Stores -> Configuration -> General -> General
2. Change Locale settings to not English (US)
3. Save
4. Clear cache
5. Open FE

**Actual result**:
Blank page 
Error message appears in the console
![Screenshot 2021-08-11 at 14 05 01](https://user-images.githubusercontent.com/73526235/129039837-e6bbfc12-8f0f-4331-a454-b7e62d6d7436.png)

**Comment by zans-laksa** [comment]
This is expected issue. The issue happens only when you set the unknown locale.
There are set of json files (da_DK.json, de_DE.json, en_US.json, es_ES.json, fa_IR.json, fi_FI.json, fr_FR.json, it_IT.json, lv_LV.json, nb_NO.json, nl_NL.json, pl_PL.json, pt_BR.json, ru_RU.json, sl_SI.json, sv_SE.json, tr_TR.json, zh_TW.json) that has supported locales.
Other locales will fail.
I've added more descriptive error message so developers will get what they should do in order to fix this on their instances.
