### ISSUE TITLE
Improve Lighthouse Scores

### ISSUE THREAD

**Issue by zans-laksa** [scandipwa/scandipwa#3126]
After 5.0.0 some lighthouse score have been decreased.
Please check our demos and improve what can be improved.
 - 40kskudemo.scandipwa.com
 - luma-demo.scandipwa.com
 - tech-demo.scandipwa.com
 - demo100-ors-1588667385-csa-qnb.scandipwa.cloud

**Comment by tatiana-scandi** [comment]
PR: https://github.com/scandipwa/scandipwa/pull/3139
Also changed several pages/blocks/widgets configurations, as they caused some of the Lighthouse warnings.

Current ratings:
https://scandipwapmrev.indvp.com/: **81** - **79** - 93 - 100
40kskudemo.scandipwa.com: 99 - **84** - 100 - **83**
luma-demo.scandipwa.com: 99 - **84** - 100 - **83**
tech-demo.scandipwa.com: 98 - **84** - 100 - **83**
demo100-ors-1588667385-csa-qnb.scandipwa.cloud: **76** - **84** - 93 - 92

Need to recheck ratings after merge and redeploy and compare (and probably optimize smth else).

**Comment by carinadues** [comment]
Checked pmrev on incognito mode: 66, 91, 93, 92.

**Comment by tatiana-scandi** [comment]
Issues left:
https://github.com/scandipwa/scandipwa/issues/3162
https://scandiweb.atlassian.net/browse/SWPWA-760

All the other issues I have been fixing are gone.

Issues not fixed intentionally:
1. `[user-scalable="no"] is used in the <meta name="viewport"> element or the [maximum-scale] attribute is less than 5.` => not fixed as otherwise we will have annoying zoom effect on iPhone with inputs font less than 16px
2. `Background and foreground colors do not have a sufficient contrast ratio.` => we have orange by design, we are not going to change this colour
