### ISSUE TITLE
Disable Component - Missing Docs

### ISSUE THREAD

**Issue by robertdeboer** [scandipwa/scandipwa#3166]
**Description**:
Unable to disable a component b/c there is no documentation on how to do so

**Expected behavior**:
If we are able to override/extend components then we should be able to disable components altogether by either overriding the list of available components or overriding the mechanism that loads the components from said list

**Screenshots, Video, Logs**
N/A

**To Reproduce**:
1. Install Theme
2. Attempt to disable a core feature: ex. product comparison
3. No documentation on how to do so and no clear place to so do in the standard extendable areas of ScandiPWA

**Versions**:
- ScandiPWA: Latest

**Additional context**:
We love the fact that any part of the ScandiPWA theme can be overwritten to suite our needs. However, while this works for most common situations there times when we do not want to enable a feature, not just override it. 

Example: Product Compare. We are creating an application for a B2B customer that does not need this feature. We know we can overwrite/extend it to add or remove functionality but we do not want the feature at all. And extending it to do nothing is not an efficient means of disabling it. And simple not showing the buttons on the site is not an efficient means either as the store still makes the initial compare API calls. We can see the file locations that list and register all the resolvers but we do not see a way to modify this list

**Comment by tatiana-scandi** [comment]
You should be able to easily exclude components included in Router config via overriding <Router/> and filtering out unneeded routes since next release:
https://github.com/scandipwa/scandipwa/pull/3111

Usage example: https://github.com/scandipwa/scandipwa/blob/bf01b54db9e057cc0dbe2be6e4f238074e6c3316/packages/scandipwa/packages/%40scandiweb/navigation-extension/src/plugin/Router.plugin.js
