### ISSUE TITLE
User appears at the bottom of the page when opening billing step from scrolled down shipping page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3290]
**Description**:
User appears at the bottom of the page when opening billing step from scrolled down shipping page

**Expected behavior**:
Page opens on the top

**To Reproduce**:
1. Open PDP
2. Add product to cart
3. Go to shipping step
4. Fill form
5. Scroll down
6. Go to billing step

**Actual result**:
Billing step is not scrolled up
https://drive.google.com/file/d/1kZ1GiKKa7Yua2_s8WWyEzo63Ar8tXIvh/view?usp=sharing

**Notes:**
The same situation with success completed order page

**Comment by carinadues** [comment]
Similar issues: #3281 and #3288

**Comment by aleksandrakorolova** [comment]
This scroll looks not good -> content loaded and then page scrolls up. Can we do the same logic as it works on other pages? (Page opens on the top and it's loading)
 https://drive.google.com/file/d/1IXrrfmceeWyfxzAyb32D29ZLUC1-cNFG/view?usp=sharing

**Comment by tatiana-scandi** [comment]
Fix applied as requested. Yet the 2 approaches differ considerably:

In the previous one the order of actions after click on "Proceed to billing" button was the following:
1. Start loading animation
2. Send request to the server to saveAddress information.
3. When SUCCESSFUL response is received, stop loader, update checkout step and URL and **scroll to top.**

In current version the order is:
1. Scroll to top
2. Send request to the server to saveAddress information.
3. When SUCCESSFUL response is received, stop loader, update checkout step and URL.

So id the expected behaviour is to scroll to top as soon as we see loading status, then option 2 is better. Yet there is a downside that if the request to the server fails and no navigation to the next checkout step happens, scroll will still be performed.

Made a video to show how it looks:

Uploading screencast 2021-12-16 16-19-54.mp4…

**Comment by Elena-Evsa** [comment]
Please, choose 1-st approach
