### ISSUE TITLE
Issues related to IOS 15

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3372]
**Expected behavior**:
all fields shown according to design

IOS 15 

**Issue 1:** 
Word 'Filters' on PLP written by blue color - Safari, Chrome 
**Screenshots, Video, Logs**
<img src="https://user-images.githubusercontent.com/84388061/134483605-75e5acbc-aeb4-47da-a60e-61a28f0bee54.png" width="250" />
**To Reproduce**:
1. Open any PLP on IOS15
----
**Issue 2:** 
Name of menu sections is blue - Safari, Chrome 
**Screenshots, Video, Logs**
<img src="https://user-images.githubusercontent.com/84388061/134484375-a82f44b7-a746-4672-a9a3-634cae4a24a4.png" width="250" />
**To Reproduce**:
1. Open My account on IOS15
----
**Issue 3:** 
White space in the bottom of write review form - Safari
**Screenshots, Video, Logs**
<img src="https://user-images.githubusercontent.com/84388061/134497604-298be649-cc48-472c-a291-1b882f965b5c.png" width="250" />
**To Reproduce**:
1. Open any product
2. Tap on 'Write review'
----
**Issue 4:** 
Space absent between bottom panel and free shipping banner in cart - Safari, Chrome 
**Screenshots, Video, Logs**
<img src="https://user-images.githubusercontent.com/84388061/134497433-ca5743a7-2e5d-44fc-9ed7-322b77bd2f83.png" width="250" />
**To Reproduce**:
1. Add some products to cart
2. Tap on cart sign
3. Scroll down
----
**Issue 5:** 
Shipping methods written by blue color - Safari, Chrome 
**Screenshots, Video, Logs**
<img src="https://user-images.githubusercontent.com/84388061/134497694-0e4d366f-9be9-428a-b5ec-40bc85f84461.png" width="250" />
**To Reproduce**:
1. Add some products to cart
2. Tap on cart sign > proceed to checkout
3. Scroll down to shipping methods
----
**Issue 6:** 
Page scrolled up when user unwrap section Details, Review - Chrome
Same if user unwrap form for enter coupon code on cart page
**Screenshots, Video, Logs**
https://vimeo.com/613545513/238e0b75ca
**To Reproduce**:
1. Open any product
2. Unwrap section Details, Review
----
**Issue 7:** 
Two loading animations appear when user deleting product from cart with help of swipe - Chrome
**Screenshots, Video, Logs**
https://vimeo.com/613549224/0c213d4cb1
**To Reproduce**:
1. Add any product to cart
2. Tap Cart sign
3. Swipe product to delete it from cart
----
**Issue 8:** 
Saved user's address is written by blue color on shipping and billing steps - Chrome
**Screenshots, Video, Logs**
<img src="https://user-images.githubusercontent.com/84388061/134671022-fd88bd6a-d935-4e1b-81d4-dfc826c7df39.png" width="250" />
**To Reproduce**:
1. Add any product to cart
2. Login in account with saved address
3. Tap Cart > Proceed to checkout
----
**Issue 9:** 
Names of payments methods are written by blue color on shipping and billing steps - Chrome
**Screenshots, Video, Logs**
<img src="![image](https://user-images.githubusercontent.com/84388061/134878253-3aa55658-224d-46b6-a3dc-f9cb16594604.png)" width="250" />
**To Reproduce**:
1. Add any product to cart
2. Login in account with saved address
3. Tap Cart > Proceed to checkout > Proceed to billing
----
**Issue 10:** 
White space appear under toolbar on menu page
**Screenshots, Video, Logs**
<img src="https://user-images.githubusercontent.com/84388061/134878467-170b6d22-f546-4771-8fe1-b80940d921ce.png" width="250" />
**To Reproduce**:
1. Open menu page

**Comment by tatiana-scandi** [comment]
1. As for blue color issues - fixable, you just need to override color, with black where needed

2. As for issue 3 and 10, which can also be reproduced for Add review Popup,  Filters popup and maybe in more cases. Investigated this issue a lot: first I was suggesting that it was odd margin / odd div, which was not visible before / issue related to `safe-area-margin-inset-bottom`. All the suggestions above turned out to be incorrect. What we really deal with is Safari's latest version bug (iOS version is 15.0). The issue can be formulated as:
     1. Open some scrollable screen
     2. Scroll it until address bar disappears
     3. make some other screen without scroll open

Result: browser window size in calculated incorrectly. Visually it looks like visible content occupies not all the space available or bottom bar is flowing, but this white area even doesn't belong to viewport.

You can notice that height of "white area" is exactly the same as address bar and height of main content is the same for cases when address bar is shown and when it is not: 
https://user-images.githubusercontent.com/79456428/134887248-0afc72a2-f12f-4745-a370-2e7e42a8eba2.mp4

And this issue is now happening throughout the world - you can open Facebook, Twitter, Instagram and find it:
![photo_2021-09-27_10-28-55](https://user-images.githubusercontent.com/79456428/134888028-d6020fea-01c7-46ca-9a60-79dae413b686.jpg)
![photo_2021-09-27_10-28-56](https://user-images.githubusercontent.com/79456428/134888030-ecd476ce-128a-4bb3-81bf-771ac68cdfd6.jpg)
![photo_2021-09-27_10-28-57](https://user-images.githubusercontent.com/79456428/134888033-88976916-c2f3-4b67-99f3-a26336997c68.jpg)
![photo_2021-09-27_10-28-58](https://user-images.githubusercontent.com/79456428/134888037-d1919d36-a9ee-403e-ad41-feccbd1b7880.jpg)

As for possibility to fix this without waiting for fix from Apple - I severely doubt this. Even if it is possible to make a fix, it will be a very dirty hack. I even tried to implement the following one:
        1. detect whether address bar is shown or not. Experimentally I found such a way to do this:
        ``` window.innerHeight !== document.documentElement.clientHeight ? 'hidden' : 'active'```
        2. If address bar is hidden, set correct content height like this:
        ```this.overlayRef.current.style.height = ${window.innerHeight - 60}px;```
And... it leads to content be of correct height. But white area below still doesn't disappear.

**Comment by zans-laksa** [comment]
1. It's better do define some global files with lesser specificity like `input, select, textarea, button { color: black }` in order to set default color for all inputs.
Then every control element will either have black color by default or custom styling it got from the classname.

**Comment by tatiana-scandi** [comment]
@zans-laksa yes, it makes sense (I've already used this approach locally, but there are more issues to fix before the PR is ready)

**Comment by tatiana-scandi** [comment]
WORK IN PROGRESS

1. Fixed (please check buttons with not black font color throughout the app, there is risk that color will be black where not needed)
2. Fixed
3. White area - no fix for now
4. TODO (same problem for billing and shipping steps - bottom of page is hidden)
5. Fixed
6. Was unable to reproduce on real device (iPhone XS). Any additional details?
7. https://github.com/scandipwa/scandipwa/pull/3414 (separate PR as not related to iOS 15)
8. Fixed
9. Fixed
10. White area - no fix for now

**Comment by Elena-Evsa** [comment]
1. Passed
2. Passed
3. Passed
4. Still can reproduce
5. Passed
6. Can not reproduce anymore
7. #3372 
8. Passed
9. Passed
10. Passed
