### ISSUE TITLE
Error message 'Minimum 8 characters!' is displayed below Password field in create an account form when submitting empty form

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3687]
**Description**:
Error messages 'This field is required!' and 'Minimum 8 characters!' are displayed below Password field in create an account form when submitting empty form

**Expected behavior**:
Error message 'This field is required!' is displayed below each empty required field

**To Reproduce**:
1. Open FE
2. Open Create an account form 
3. Click on Create an account

**Versions**:
Error messages 'This field is required!' and 'Minimum 8 characters!' are displayed below Password field
![Screenshot 2021-11-04 at 10 23 26](https://user-images.githubusercontent.com/73526235/140280960-35af63d7-d3a9-480f-aadc-993b7a72d5df.png)

**Comment by Elena-Evsa** [comment]
Boarders of field for enter password red color in case if user made mistake and click on 'Save', error message about Qty of different classes does not appear and validation shown under the field with password, but it can not very good because of length of error's text
https://vimeo.com/664207750/d9d175e664
Same logic absent for field for enter password on create account popup and page, 'Change My Password' page, could you, please, implement it 
Now on the page 'Edit Account Information':
![image](https://user-images.githubusercontent.com/84388061/148760648-8b24855b-bbd2-4319-8b82-fbc51d450fce.png)
