### ISSUE TITLE
Arrow back is not centralized near title on PLP on Mobile 

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3734]
**Description**:
Arrow back is not centralized near title on PLP

**Expected behavior**:
Arrow back is centralized near title on PLP

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/140909842-9fd360e6-6601-41e8-a3ad-372e0434a85b.png)

**To Reproduce**:
1. Open any PLP on mobile

**Actual result**:
Arrow back is not centralized near title on PLP

**Comment by aleksandrakorolova** [comment]
It looks good on iOS:
![Screenshot 2021-11-15 at 09 05 43](https://user-images.githubusercontent.com/73526235/141737072-62e73537-69da-4cc7-9b41-51f9027ca637.png)

Arrow is shifted down on Android devices:
![Screenshot 2021-11-15 at 08 59 43](https://user-images.githubusercontent.com/73526235/141736765-fe95a525-9ceb-4919-bbe4-5b1079448fbe.png)

**Comment by tatiana-scandi** [comment]
First thing to note is 1. arrow is vertically  aligned 2. h1 tag is vertically aligned 3. content inside h1 tag is stuck to top:|
TBD

This issue is related to font `Muli`, which we're using. On android devices it's aligned to top of text area. On desktop Chrome and iOS Chrome/Safari it is centered.

With `sans-serif` font family (it's our fallback if `Muli` is not available), header is centered correctly on all devices. I see some hacks in our code trying to make it nicer (via `line-height` and `height` for `h1`), but they won't play well across all devices/OS.
On android we have similar issue for some other UI elements, e.g. for `Add to cart` button. Header is just easier to notice due to its large size.

Here is JSfiddle with minimal reproducible example: https://jsfiddle.net/d17r64pv/3/
Screenshot:
![image](https://user-images.githubusercontent.com/79456428/142908923-5c8e602b-b09c-4a02-bad9-85918af2fdb9.png)

If Muli is replaced with other font, the issue is not reproducible on Android devices:
TBD

So, I have pending thing to check - try to find out how current https://use.typekit.net/fji5tuz.css link for font-faces data has been generated + if Adobe fonts give possibility to generate some OS specific font versions.

If nothing relevant found, there are 3 options 1. change global font 2. change Android font (for 1 and 2 there is risk that lots of UI elements will look broken/ not as before on Android; for 2 there is a problem that if another font is used for a specific OS, testing scope increases significantly on all stages) 3. live with that (which is not a bad option as most projects do override ScandiPWA fonts).

**Comment by tatiana-scandi** [comment]
I used https://fonts.adobe.com/fonts/muli page to generate another font-face config: https://use.typekit.net/qcb0ufv.css

Tried using it on Android phone again => the issue is not gone (https://jsfiddle.net/tappiola/u08L2cqs/1/). So there is no proper way to avoid this issue on Android devices, if Muli is used.

**Comment by Elena-Evsa** [comment]
Thanks for investigating, let left it
