### ISSUE TITLE
Section with featured products blinking and scroll appear on home page when user hover on it on 40SKUDEMO

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3801]
**Description**:
Section with featured products blinking and scroll appear on the home page when user hover on it on 40SKUDEMO

**Expected behavior**:
Product card shown without blinking when the user hovers on it, there is no scroll bar and the products appear over the footer.

**Screenshots, Video, Logs**
https://vimeo.com/646439918/89d8cf6baa

**To Reproduce**:
1. Open https://40kskudemo.scandipwa.com/de_storeview/
2. Hover on the second line of products of featured products

**Actual result**:
Section with featured products blinking and scroll appear on the page when user hover on it

**Comment by Mohamed-Ahmed711** [comment]
The solution to this issue is in Magento Admin panel -> Content-> Blocks-> Homepage Jeans Preview DE ->Edit

![Homepage Jeans Preview DE - Blocks - Elements - Content - Magento Admin 2022-03-10 02-10-23](https://user-images.githubusercontent.com/99433797/157561655-dfda0650-a2b1-47c6-8601-4160e2a3651c.png)

![Screenshot from 2022-03-10 01-51-00](https://user-images.githubusercontent.com/99433797/157561669-127ee311-9a13-4f41-9783-22026f61c16c.png)
