### ISSUE TITLE
Support for Magento 2.4.4

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#4122]
**Description**:
Magento 2.4.4 coming out on March 8th with PHP 8.1. Let's add support for it.

https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-4.html

**Additional info**:
The Magento Performance Test build showed that updating PHP to 8.1 improves Magento performance by 10-15% compared to 7.4.

**Comment by AzizKHAN030** [comment]
**1.** Installed db from scandipmrev

**2.** Got an error in file `/localmodules/cms-graphql/src/Model/Template/Filter.php` that the required variables are declared after optional(with default values) since it is required in PHP 8
- Reordered the variables

**3.** Got an error in `/localmodules/persisted-query/src/Query/QueryProcessor.php:106`
- Couldn't find Debug class because it was renamed to DebugFlag

**4.**  Got error in `localmodules/catalog-graphql/src/Model/Layer/Filter/Category.php` that in parent::__construct only 5 params were passed and in newer version it needs  6 params
- Passed the 6th param  $includeDirectChildrenOnly class.
-  Now I can get the product filters but I'm getting sort_fields as null and error for that issue

**Comment by AzizKHAN030** [comment]
**1.** Got error in `localmodules/catalog-graphql/src/Model/Resolver/Category/SortFields.php` that sort_fields should be an array. 

- Declared a variable as array and filters started working

**Comment by AzizKHAN030** [comment]
**Platform enhancements**

- Magento Open Source 2.4.4 provides support for Elasticsearch 7.16 and OpenSearch 1.2. Magento Open Source merchants with deployments hosted on-premises can use either solution. However, OpenSearch is now the default search engine for Magento Open Source 2.4.4 deployments hosted in the cloud. All customers with cloud deployments who upgrade to version 2.4.4 must use OpenSearch. See [Switching to OpenSearch for Adobe Commerce on Cloud 2.4.4](https://support.magento.com/hc/en-us/articles/4419942355725-Switching-to-OpenSearch-for-Adobe-Commerce-on-Cloud-2-4-4?_ga=2.230405083.671308567.1651564736-537813238.1650422652)

 
**Vendor-Bundled Extensions**

- All the vendor extensions such as Amazon Pay, dotdigital, Klarna, Vertex, YotPo have been removed from M2.4.4, only Braintree wasn’t because it is integrated to core Magento


**PayPal Payment enhancements**

- The Venmo payment option is now supported.
- Pay Later has been added as an option for shoppers based on the shopper’s location, not the merchant’s location.

**Slider**

- Merchants can now add alternative text (alt_text) to images (Image, Banner, Slide) to enhance content accessibility. [GitHub-746](https://github.com/magento/magento2-page-builder/issues/746)  In Page builder

 
**Cart and checkout**

- Shoppers can now place orders without errors after a session timeout in deployments where persistent shopping cart is enabled. Previously, Magento Open Source displayed a payment error after a session timeout. (the shopper is logged out while doing checkout)

 
**GraphQL**

- When the price of a tier product is updated from the backend, the new price is updated correctly on the customer’s cart. Previously, although the subtotal in the cart summary section was updated correctly, the row subtotal was not updated. (Works well in 2.4.4 unlike the 2.4.3)
- products query layered navigation filters now return correct child categories lists. Only direct subcategories are now included when the includeDirectChildrenOnly flag is provided in the request. Previously, all categories were included in response in the aggregation section when a product was assigned to several categories. ([Resolved in catalog-graphql](https://github.com/scandipwa/scandipwa/issues/4122#issuecomment-1111184033))

**Comment by AzizKHAN030** [comment]
**GraphQL**

- The generateCustomerToken and revokeCustomerToken mutations now provide the correct cache ID for the user state. Previously, these mutations used an invalid x-magento-cache-id, which degraded performance.
- The addProductsToCart mutation now adds to the cart only products that are assigned to the store that is defined in the header.
- The products query now returns only configurable variants that are assigned to the requested storeview. Previously, all variants of the requested configurable product were returned.
- The addProductsToCompareList mutation can now be used to compare variants of configurable products.
- The addProductsToCart mutation now adds all selected options to the cart when used to add bundle products with multiple selection options. Previously, the mutation added only the last selection. [GitHub-33123](https://github.com/magento/magento2/issues/33123)

 
**Payment methods**

- PayPal can now track by BN code.
- PayPal Express now works as expected from the shopping cart. Previously, when you clicked the PayPal button to start express checkout from the cart, Magento Open Source threw this error: To check out, please sign in with your email address. [GitHub-33445](https://github.com/magento/magento2/issues/33445)
- Shoppers are now redirected to the success page as expected after payment with PayPal Payments Advanced payment completes. Previously, shoppers were not redirected to this page even though the payment was successfully processed and no errors were logged.

**Performance**

- Magento Open Source by default resizes images synchronously during product save. Merchants can now resize images as a background asynchronous process by minor edits to a di.xml file.

**Comment by AzizKHAN030** [comment]
**Notice**
- Merchants can now add alternative text (alt_text) to images (Image, Banner, Slide) to enhance content accessibility. https://github.com/magento/magento2-page-builder/issues/746 In Page builder

It would be better to add this kind of option for scandipwa slider and and images in order to improve SEO.

**Comment by AzizKHAN030** [comment]
**Notice**
- Merchants can now add alternative text (alt_text) to images (Image, Banner, Slide) to enhance content accessibility. https://github.com/magento/magento2-page-builder/issues/746 In Page builder

It would be better to add this kind of option for scandipwa slider and and images in order to improve SEO.

**Comment by AzizKHAN030** [comment]
Closed by accident =)

**Comment by AzizKHAN030** [comment]
**Klarna**

The [klarna-graphql](https://github.com/scandipwa/klarna-graphql) module is not compatible with the klarna extension from magento 2.4.4 since it doesn't have GraphQL support. From our side, we should disable klarna for now.

**Comment by AzizKHAN030** [comment]
**Note for installation locally**

- all the scandipwa required dependencies should be required as "dev-master as x.x.x" version
