### ISSUE TITLE
Mobile: CMS block is displayed between products and order subtotal on checkout pages

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4228]
**Description**:
Mobile: CMS block is displayed between products and price on checkout

**Expected behavior**:
CMS block is displayed between price and shipping/billing form

**To Reproduce**:
1. Open PDP in mobile layout
2. Add product to cart
3. Open Cart
4. Open summary block

**Actual result**:
CMS block is displayed between products and price
![Screenshot 2022-02-02 at 15 21 12](https://user-images.githubusercontent.com/73526235/152162009-1a33a8a2-c9de-4143-ba77-ca69ffc8d81d.png)

**Comment by Elena-Evsa** [comment]
Line is bold (or doubling) if user unwraps section with summary on shipping / billling step 
![image](https://user-images.githubusercontent.com/84388061/160137217-7b04258e-11ce-4d58-bce4-22397ffbde38.png)

**Comment by Elena-Evsa** [comment]
CMS block absent
![image](https://user-images.githubusercontent.com/84388061/161002937-6573583d-f757-46c1-a30b-963b07e74595.png)

**Comment by AzizKHAN030** [comment]
This bug is not related to my PR cuz I changed only styles and other would be HTML at least, but there is no CmsBlock itself in the component. And there is the cmsBlock in my branch for that issue. 
![image](https://user-images.githubusercontent.com/76899788/161081604-a5a145e0-d39b-407d-8f17-482a9cfc3854.png)
