### ISSUE TITLE
Count for options is moved to the next line without the last word in Layered Navigation 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4282]
**Description**:
Count for options is moved to the next line without the last word in Layered Navigation 

**Expected behavior**:
Move last word of option with Qty on the next line

**To Reproduce**:
1. Go to /women page

**Actual result**:
Qty of products is displayed in next line
![Screenshot 2022-02-11 at 12 25 27](https://user-images.githubusercontent.com/73526235/153575999-bdbd8b2e-ec9f-4f29-a596-8d14b1fe3867.png)

**Comment by pablobentivengo** [comment]
Hey! I was checking the issue, after some testing I concluded that the issue is being generated because the input value has an additional space. I added the .trim() to the value and this is the result. As you can see the line break is working fine, but at the dev inspector on the **label** and **input** attributes it can be seen that they have an additional space at the end. I think we should fix this preventing the info from the BE being submitted without trimming.

1)**Blank spaced marked**
![image](https://user-images.githubusercontent.com/97158749/153619287-e63d5a76-cb1b-4480-a14a-6622707c1e37.png)

2)**Blank space removed**
![image](https://user-images.githubusercontent.com/97158749/153614334-61b62114-0946-4c3a-8a2f-bb1354bd4b66.png)
