### ISSUE TITLE
Input type=“number” isn't supported

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4312]
**Description**:
Input type=“number” isn't supported

**Expected behavior**:
input type=“number” is supported

**To Reproduce**:
1. Open PDP 
2. Add product to cart
3. Open Shipping step
4. Open Console
5. Change input type to type=“number”

**Actual result:**:
input type=“number” isn't supported
![Screenshot 2022-02-18 at 11 22 25](https://user-images.githubusercontent.com/73526235/154654856-f5fd8979-27af-4bce-8dd3-b8c731a00524.png)

**Comment by zans-laksa** [comment]
@carinadues @aleksandrakorolova 

This task requires a deeper explanation.
On the one hand, we have a custom number field with quantity controls. On the other hand, we might need the regular number field, without the additional elements.
Those are the two different components, they have different appearances and different behavior.
So what does the expected behavior "input type=“number” is supported" actually means?
I suggest implementing the number field in two versions and using the appropriate components in the case it was designed for.
