### ISSUE TITLE
Cache issue on PDP when updating Qty, Price or Name and no manual refresh

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4778]
**Description**:
There's a cache issue that PDP changes are not happening if you come to the same PDP. You need to navigate to a new PDP to see them: if you navigate to a PLP/CMS and come back to the first PDP, you won't see the changes unless you do a manual refresh. So if you change the Qty, Price, or Name in the admin panel, these things should update as the user browses around, especially considering InApp situations. 

Below see the steps for the case of Stock. In the comments, there's more about Price and Name changing.

**Screenshots, Video, Logs**
https://vimeo.com/709430208/c64e8b9adc

**To Reproduce**:
On FE:
1. Open any ‘In stock’ product on PDP and PLP
2. Add to the cart 10 items
3. Complete order
4. Add to cart same product

In Admin panel:
5. Open the same product from step 4
6. Set Qty of product = 5
7. Save
8. Check the amount in stock in tab 'Product Salable Quantity' , it should be less than 0

On FE:
9. Open PLP with product
10. Hover on the product card
11. Click on the product card
12. Click on mini cart

**Expected behavior**:
If updating Qty of product in admin, then stock status changes:
11. Status changed on PDP 
12. Status changed in Cart

**Actual result**:
10. Status changed on PLP
11. PDP stays the same as for 'In stock' product
12. Cart stays the same as for 'In stock' product

**Comment by Elena-Evsa** [comment]
Same if user changes in steps 5-6 Price of product
Actual result: if user adds the product to cart after changing of price, then the product with the new price added to cart.

**Comment by carinadues** [comment]
Same if you change the name of the product in the admin panel.

**Expected behavior**:
When you change qty, name, or price and then browse around, the product should update for the user. 

**Actual result**:
Right now you only see the product updating if you browse between the same type of page.
If you go from PLP to PDP, you won't see PDP updating.
But if you go to another PDP and then back to the first PDP, it will update.

On the cart, it depends on what the customer wants. Right now it doesn't update, but if you change something in the product in the cart, like increase qty, it will change.
