### ISSUE TITLE
Unified interface for plugins

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/scandipwa#897]
**Description**:
When working with plugins I found that the arguments type & arguments order is different between:
- member-functions
- member-property

Specifically:
- for member-functions: [array, callback, proxy object]
- for member-properties: [callback, proxy object]

The docs are outdated so I couldn't figure what should array argument passed to member-function should represent but I see it's always empty!

**Expected behavior**:
I think all plugins should have the same interface.

**Additional context**:
Issue was originally reported by @salah-ahmed in https://github.com/scandipwa/scandipwa-base/issues/112

**Comment by yeegor** [comment]
The `member-properties` have no arguments, neither should they.

We can have `callback, instance, args` instead of `args, callback, instance` for everything - that would increase the proximity of two APIs, or even `{ args, callback, instance }`, but at the current moment, it'd confuse some people whose plugins would stop working. All the existing plugins would stop working... 

What do you think?

**Comment by alfredsgenkins** [comment]
Despite this idea is good indeed, we have already documented the proper APIs, and there are a lot of extensions relying on it. Let's keep it this way! https://docs.create-scandipwa-app.com/extensions/application-plugins#proxy-function-implementation-types
